// Generates static SVG path data for the globe on the landing page.
// Run: node scripts/build-geo.mjs  (output: src/generated/geo.ts)
import { readFileSync, writeFileSync } from "node:fs";
import { geoOrthographic, geoPath, geoGraticule10 } from "d3-geo";
import { feature, merge } from "topojson-client";

const load = (res) =>
  JSON.parse(readFileSync(new URL(`../node_modules/world-atlas/${res}`, import.meta.url)));

const world110 = load("countries-110m.json");
const countries110 = feature(world110, world110.objects.countries).features;

// ISO 3166-1 numeric ids used by world-atlas
// 12 zemí na 3 kontinentech, jako v návrhu webu
const VISITED = ["203", "703", "040", "276", "191", "380", "300", "008", "268", "620", "724", "504"];
const WISHLIST = ["352", "818", "400"];

const r = (s) => s ?? "";

// Globe: viewBox 0 0 200 200, sphere r=96 centered like the app design
const globe = geoOrthographic().scale(96).translate([100, 100]).rotate([-18, -36]).clipAngle(90);
const gp = geoPath(globe).digits(1);

const land = gp(merge(world110, world110.objects.countries.geometries));
const visited = countries110.filter((f) => VISITED.includes(f.id)).map((f) => r(gp(f))).join("");
const wishlist = countries110.filter((f) => WISHLIST.includes(f.id)).map((f) => r(gp(f))).join("");
const graticule = gp(geoGraticule10());
// Připínáčky: tipy kamarádů (Batumi, Theth) a jeden na wishlistu (Káhira)
const globePins = [
  { lon: 41.64, lat: 41.64, kind: "tip" },
  { lon: 19.77, lat: 42.39, kind: "tip" },
  { lon: 31.24, lat: 30.04, kind: "wish" },
].map((p) => {
  const [x, y] = globe([p.lon, p.lat]);
  return { kind: p.kind, x: Math.round(x * 10) / 10, y: Math.round(y * 10) / 10 };
});

const out = `// Generated by scripts/build-geo.mjs. Do not edit by hand.
// Map data: Natural Earth via world-atlas (public domain).

export const globeLand = ${JSON.stringify(land)};
export const globeVisited = ${JSON.stringify(visited)};
export const globeWishlist = ${JSON.stringify(wishlist)};
export const globeGraticule = ${JSON.stringify(graticule)};
export const globePins = ${JSON.stringify(globePins)} as const;
`;
writeFileSync(new URL("../src/generated/geo.ts", import.meta.url), out);
console.log("geo.ts", (out.length / 1024).toFixed(1), "kB");
