// Generates static SVG path data for the landing page illustrations.
// Run: node scripts/build-geo.mjs  (output: src/generated/geo.ts)
import { readFileSync, writeFileSync } from "node:fs";
import { geoOrthographic, geoMercator, geoPath, geoGraticule10 } from "d3-geo";
import { feature, merge } from "topojson-client";

const load = (res) =>
  JSON.parse(readFileSync(new URL(`../node_modules/world-atlas/${res}`, import.meta.url)));

const world110 = load("countries-110m.json");
const world50 = load("countries-50m.json");
const countries110 = feature(world110, world110.objects.countries).features;
const countries50 = feature(world50, world50.objects.countries).features;

// ISO 3166-1 numeric ids used by world-atlas
const VISITED = ["203", "703", "040", "276", "616", "348", "191", "380", "300", "008", "499", "268", "792", "620", "724", "250", "504", "578", "705"];
const WISHLIST = ["352", "818", "400"];

const r = (s) => s ?? "";

// Globe: viewBox 0 0 200 200, sphere r=96 centered like the app design
const globe = geoOrthographic().scale(96).translate([100, 100]).rotate([-18, -36]).clipAngle(90);
const gp = geoPath(globe).digits(1);

const land = gp(merge(world110, world110.objects.countries.geometries));
const visited = countries110.filter((f) => VISITED.includes(f.id)).map((f) => r(gp(f))).join("");
const wishlist = countries110.filter((f) => WISHLIST.includes(f.id)).map((f) => r(gp(f))).join("");
const graticule = gp(geoGraticule10());

// Georgia map for the "tipy kamarádů" illustration: 320 x 180
const georgia = countries50.find((f) => f.id === "268");
const merc = geoMercator().fitExtent([[16, 18], [304, 162]], georgia);
const mp = geoPath(merc).digits(1);
const pins = [
  { id: "tbilisi", name: "Tbilisi", lon: 44.79, lat: 41.72, who: "PN" },
  { id: "kazbegi", name: "Kazbegi", lon: 44.64, lat: 42.66, who: "AK" },
  { id: "batumi", name: "Batumi", lon: 41.64, lat: 41.64, who: "KM" },
  { id: "mestia", name: "Mestia", lon: 42.73, lat: 43.05, who: "TH" },
].map((p) => {
  const [x, y] = merc([p.lon, p.lat]);
  return { ...p, x: Math.round(x), y: Math.round(y) };
});
const gems = [
  { lon: 43.28, lat: 41.38 }, // Vardzia
  { lon: 45.92, lat: 41.62 }, // Sighnaghi
].map((p) => merc([p.lon, p.lat]).map(Math.round));

const out = `// Generated by scripts/build-geo.mjs. Do not edit by hand.
// Map data: Natural Earth via world-atlas (public domain).

export const globeLand = ${JSON.stringify(land)};
export const globeVisited = ${JSON.stringify(visited)};
export const globeWishlist = ${JSON.stringify(wishlist)};
export const globeGraticule = ${JSON.stringify(graticule)};

export const georgiaOutline = ${JSON.stringify(mp(georgia))};
export const georgiaPins = ${JSON.stringify(pins)} as const;
export const georgiaGems = ${JSON.stringify(gems)} as const;
`;
writeFileSync(new URL("../src/generated/geo.ts", import.meta.url), out);
console.log("geo.ts", (out.length / 1024).toFixed(1), "kB");
